### ISSUE TITLE
AS-11 Spec links with fragments don't always auto-scroll on page open

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#140] opened 2021-02-12 16:34 UTC
Example: https://amwa-tv.github.io/AS-11_X6/AMWA_AS_11_X6.html#63f8f5d8a43ac949c769a97ab564f048

It looks like it's the tree entries without any children that are affected.

**Comment by Matthew-Marks** [comment] 2021-05-13 14:01
I've noticed the published renders have an old version of the Javascript which doesn't contain my fix for this. It looks like I created them with an older commit of the rules-processor, and that is confirmed from `githashes.json`. So this should sort itself out the next time the renders are updated. Will close for now - can be re-opened of necessary.

**Comment by Matthew-Marks** [comment] 2021-05-25 15:21
Now fixed in latest updates to Spec renderings.

**Closed as completed by Matthew-Marks** 2021-05-25 15:21 UTC
Labels: bug, Active
